#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d       

bspc config border_width         2
bspc config window_gap           4
bspc config click_to_focus        true
bspc config focused_border_color "#D705F2"
bspc config normal_border_color "#F39FF4"
# bspc config active_border_color "#030A8C"
# bspc config presel_feedback_color "#6272a4"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a code                desktop='^1'
bspc rule -a tilix               desktop='^1'
bspc rule -a Google-chrome       desktop='^2'
bspc rule -a telegram-desktop    desktop='^3'
bspc rule -a obs                 desktop='^4'


# bspc rule -a telegram-desktop desktop='^4' state=floating follow=on
# bspc rule -a telegram-desktop desktop='^3' follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# $HOME/.config/polybar/launch.sh
feh --bg-scale $HOME/.config/wallpapers/7.jpg
pulseaudio &
wal -R 
xsetroot -cursor_name left_ptr

numlockx 
setxkbmap us

